INSERT INTO burgers (burger_name, devoured, date) 
VALUES ('The Mack', false, now())
, ('Big Devil', false, now())
, ('The Ghetto Burger', false, now())
, ('The Primetime', false, now())
, ('The Black Label Burger', true, now())	